import { useState, useEffect } from 'react';
import { X, Loader2 } from 'lucide-react';
import api from '../api/client';
import type { ControlledDocument, DocumentTemplate } from '../types';
import toast from 'react-hot-toast';
import { showErrorToast } from '../utils/errorHandler';

interface Props {
  open: boolean;
  doc: ControlledDocument;
  onClose: () => void;
  onSuccess: (doc: ControlledDocument) => void;
}

export default function QAPreparationModal({ open, doc, onClose, onSuccess }: Props) {
  const [templates, setTemplates] = useState<DocumentTemplate[]>([]);
  const [selectedTemplateId, setSelectedTemplateId] = useState('');
  const [previewNumber, setPreviewNumber] = useState('');
  const [loading, setLoading] = useState(false);
  const [loadingTemplates, setLoadingTemplates] = useState(false);

  useEffect(() => {
    if (!open) return;
    setPreviewNumber('');
    setSelectedTemplateId('');

    // Fetch latest active templates for this document type
    setLoadingTemplates(true);
    api.get<DocumentTemplate[]>('/templates', { params: { documentTypeId: doc.documentTypeId } }).then(res => {
      const latest = res.data.filter(t => t.active && t.latest);
      const list = latest.length > 0 ? latest : res.data.filter(t => t.active);
      setTemplates(list);
    }).catch(() => setTemplates([]))
      .finally(() => setLoadingTemplates(false));

    // Fetch preview of auto-generated document number
    api.get<{ documentNumber: string }>(`/documents/preview-number`, {
      params: { documentTypeId: doc.documentTypeId, unitId: doc.unitId }
    }).then(res => {
      setPreviewNumber(res.data.documentNumber);
    }).catch(() => {});
  }, [open, doc.documentTypeId, doc.unitId]);

  if (!open) return null;

  const selectedTemplate = templates.find(t => t.id === selectedTemplateId);

  const handleSubmit = async () => {
    if (!selectedTemplateId) {
      toast.error('Please select a template');
      return;
    }
    setLoading(true);
    try {
      const res = await api.post<ControlledDocument>(`/documents/${doc.id}/prepare`, {
        documentNumber: null, // always auto-generate
        templateId: selectedTemplateId,
      });
      toast.success(`Document prepared: ${res.data.documentNumber}`);
      onSuccess(res.data);
      onClose();
    } catch (err) {
      showErrorToast(err, 'Failed to prepare document');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40" onClick={onClose}>
      <div className="bg-white rounded-lg shadow-xl w-full max-w-md mx-4" onClick={e => e.stopPropagation()}>
        <div className="px-5 py-4 border-b border-gray-200 flex items-center justify-between">
          <h3 className="text-base font-semibold text-gray-900">Select Document</h3>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600"><X size={18} /></button>
        </div>

        <div className="p-5 space-y-4 relative">
          {loading && (
            <div className="absolute inset-0 bg-white/80 z-10 flex flex-col items-center justify-center gap-2">
              <Loader2 size={24} className="animate-spin text-gray-500" />
              <p className="text-sm text-gray-500 font-medium">Preparing document...</p>
              <p className="text-xs text-gray-400">Assigning template and generating document number</p>
            </div>
          )}
          {/* Document info */}
          <div className="bg-gray-50 rounded-lg p-3.5">
            <p className="font-medium text-gray-900 text-sm">{doc.title}</p>
          </div>

          {/* Auto-generated document number — read-only */}
          <div>
            <label className="block text-xs font-medium text-gray-500 mb-1">Document Number</label>
            <div className="font-mono text-sm font-semibold text-gray-800 bg-gray-50 border border-gray-200 rounded-md px-3 py-2">
              {previewNumber || <span className="text-gray-400">Generating...</span>}
            </div>
            <p className="text-[11px] text-gray-400 mt-1">Auto-generated by system</p>
          </div>

          {/* Template dropdown */}
          <div>
            <label className="block text-xs font-medium text-gray-500 mb-1">Select Template</label>
            {loadingTemplates ? (
              <div className="flex items-center gap-2 text-sm text-gray-400 py-2">
                <Loader2 size={14} className="animate-spin" /> Loading templates...
              </div>
            ) : templates.length > 0 ? (
              <>
                <select
                  className="input text-sm"
                  value={selectedTemplateId}
                  onChange={e => setSelectedTemplateId(e.target.value)}
                >
                  <option value="">— Select a template —</option>
                  {templates.map(t => (
                    <option key={t.id} value={t.id}>
                      {t.name} (v{t.version}){t.latest ? ' — Latest' : ''}
                    </option>
                  ))}
                </select>
                {selectedTemplate?.description && (
                  <p className="text-xs text-gray-500 mt-1.5">{selectedTemplate.description}</p>
                )}
              </>
            ) : (
              <div className="text-sm text-gray-500 italic py-2 px-3 bg-yellow-50 rounded-lg border border-yellow-100">
                No templates available for this document type
              </div>
            )}
          </div>

          {/* Summary */}
          {selectedTemplateId && (
            <div className="bg-gray-50 rounded-lg p-3 border border-gray-100">
              <p className="text-[10px] font-semibold text-gray-400 uppercase tracking-wide mb-1.5">Summary</p>
              <div className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-1 text-xs">
                <span className="text-gray-500">Number:</span>
                <span className="font-mono font-medium text-gray-800">{previewNumber || '—'}</span>
                <span className="text-gray-500">Template:</span>
                <span className="text-gray-800">{selectedTemplate?.name} v{selectedTemplate?.version}</span>
                <span className="text-gray-500">Next Step:</span>
                <span className="text-gray-800">Author Draft</span>
              </div>
            </div>
          )}
        </div>

        <div className="px-5 py-3 border-t border-gray-200 flex justify-end gap-2">
          <button className="text-sm px-4 py-1.5 border border-gray-200 text-gray-600 hover:bg-gray-50 rounded-md" onClick={onClose}>
            Cancel
          </button>
          <button
            className="btn-primary text-sm px-4 py-1.5"
            onClick={handleSubmit}
            disabled={loading || !selectedTemplateId}
          >
            {loading ? <><Loader2 size={14} className="animate-spin" /> Selecting...</> : 'Select & Assign to Author'}
          </button>
        </div>
      </div>
    </div>
  );
}
