package com.pharmaCx.dms.domain.enums;

public enum AuditAction {
    // Document lifecycle
    DOCUMENT_REQUESTED,
    DOCUMENT_PREPARED,
    DOCUMENT_NUMBER_ASSIGNED,
    DOCUMENT_TEMPLATE_APPLIED,
    DOCUMENT_DRAFTED,
    DOCUMENT_SUBMITTED_FOR_REVIEW,
    DOCUMENT_PEER_REVIEWED,
    DOCUMENT_QA_REVIEWED,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    DOCUMENT_PUBLISHED,
    DOCUMENT_RETIRED,
    DOCUMENT_REVISION_INITIATED,

    // Document content changes
    DOCUMENT_CONTENT_EDITED,
    DOCUMENT_PAGE_MODIFIED,
    DOCUMENT_SECTION_MODIFIED,
    DOCUMENT_COMMENT_ADDED,
    DOCUMENT_COMMENT_RESOLVED,
    DOCUMENT_VERSION_CREATED,
    DOCUMENT_CONTENT_RESTORED,
    DOCUMENT_CHANGE_AFTER_REJECTION,

    // Document access actions (always captured — allowed or blocked)
    DOCUMENT_DOWNLOAD_ATTEMPTED,
    DOCUMENT_DOWNLOAD_BLOCKED,
    DOCUMENT_PRINT_ATTEMPTED,
    DOCUMENT_PRINT_BLOCKED,
    DOCUMENT_UPLOAD_ATTEMPTED,
    DOCUMENT_UPLOAD_BLOCKED,

    // Workflow actions
    WORKFLOW_STEP_ASSIGNED,
    WORKFLOW_STEP_STARTED,
    WORKFLOW_STEP_COMPLETED,
    WORKFLOW_STEP_REJECTED,
    WORKFLOW_REASSIGNED,

    // Folder management
    FOLDER_CREATED,
    FOLDER_UPDATED,
    FOLDER_DELETED,
    FOLDER_POLICY_CREATED,
    FOLDER_POLICY_UPDATED,
    FOLDER_OWNER_ASSIGNED,
    FOLDER_PERMISSION_CHANGED,

    // Organizational units
    ORG_UNIT_CREATED,
    ORG_UNIT_UPDATED,
    ORG_UNIT_DEACTIVATED,

    // Document type configuration
    DOCUMENT_TYPE_CREATED,
    DOCUMENT_TYPE_UPDATED,
    DOCUMENT_TYPE_DEACTIVATED,

    // IP access control
    IP_ACCESS_GRANTED,
    IP_ACCESS_BLOCKED,
    IP_POLICY_CREATED,
    IP_POLICY_UPDATED,
    IP_POLICY_REVOKED,

    // Training
    TRAINING_ASSIGNED,
    TRAINING_STARTED,
    TRAINING_DOCUMENT_OPENED,
    TRAINING_DOCUMENT_READ,
    TRAINING_QUIZ_ATTEMPTED,
    TRAINING_QUIZ_PASSED,
    TRAINING_QUIZ_FAILED,
    TRAINING_ACKNOWLEDGED,
    TRAINING_COMPLETED,
    TRAINING_OVERDUE,

    // User/Auth
    USER_LOGIN,
    USER_LOGOUT,
    USER_CREATED,
    USER_UPDATED,
    USER_DEACTIVATED,
    USER_EDITOR_PERMISSIONS_CHANGED,
    PASSWORD_CHANGED,

    // E-Signature
    ESIGNATURE_APPLIED,
    ESIGNATURE_VERIFIED,

    // System
    TEMPLATE_CREATED,
    TEMPLATE_UPDATED,
    TEMPLATE_DELETED,
    SYSTEM_SETTING_CHANGED,
    AUDIT_LOG_EXPORTED,

    // AI (CFR 21 Part 11 — every AI interaction must be logged)
    AI_QUERY_EXECUTED,
    AI_CLOUD_OUTBOUND,
    AI_LOCAL_EXECUTED,
    REINDEX_TRIGGERED
}
